"""
project_tracker.py — Project activity scanning, category management,
CLAUDE.md generation, Claude Desktop registration.

New tools:
  scan_project_folder      — detect work done since last scan (git, files, todos)
  scan_folder_for_intent   — auto-detect project purpose from folder contents
  update_all_projects      — scan every registered project folder
  link_claude_desktop      — register a project in Claude Desktop's config
  get_project_categories   — list all categories in use
  set_project_category     — assign/rename a project's category
"""

import datetime
import json
import os
import re
import subprocess
from pathlib import Path

from mcp.types import TextContent

from metis_mcp.config import paths
from metis_mcp.db import connect
from metis_mcp.app_instance import app


# ── Helpers ───────────────────────────────────────────────────────────────────

def _ensure_columns(conn) -> None:
    existing = {row[1] for row in conn.execute("PRAGMA table_info(projects)")}
    for col, defn in [
        ("category",       "TEXT DEFAULT ''"),
        ("last_scanned",   "TEXT DEFAULT NULL"),
        ("scan_summary",   "TEXT DEFAULT ''"),
        ("claude_desktop_linked", "INTEGER DEFAULT 0"),
    ]:
        if col not in existing:
            conn.execute(f"ALTER TABLE projects ADD COLUMN {col} {defn}")


def _wsl_to_windows(path: str) -> str:
    """Convert /mnt/c/... to C:\\... for Windows tool calls."""
    m = re.match(r"^/mnt/([a-zA-Z])/(.*)", path)
    if m:
        return m.group(1).upper() + ":\\" + m.group(2).replace("/", "\\")
    return path


def _windows_to_wsl(path: str) -> str:
    """Convert C:\\... to /mnt/c/..."""
    m = re.match(r"^([A-Za-z]):[/\\](.*)", path)
    if m:
        return f"/mnt/{m.group(1).lower()}/{m.group(2).replace(chr(92), '/')}"
    return path


def _resolve_folder(external_path: str) -> Path | None:
    if not external_path:
        return None
    candidates = [Path(external_path), Path(_windows_to_wsl(external_path))]
    for p in candidates:
        if p.exists():
            return p
    return None


def _write_claude_md(folder: Path, project: dict, tasks: list[dict]) -> bool:
    """Write/refresh CLAUDE.md in the project folder."""
    open_tasks = [t for t in tasks if t.get("status") not in ("done", "cancelled")]
    done_tasks  = [t for t in tasks if t.get("status") == "done"]
    category = project.get("category") or project.get("domain") or "Research"
    lines = [
        f"# {project['title']}",
        "",
        f"**Category:** {category}  ",
        f"**Project ID:** `{project['project_id']}`  ",
        f"**Status:** {project.get('status', 'active')}",
        "",
    ]
    if project.get("description"):
        lines += ["## About this project", project["description"], ""]
    if project.get("next_step"):
        lines += ["## Current focus", project["next_step"], ""]
    if open_tasks:
        lines.append("## Open tasks")
        for t in open_tasks[:10]:
            lines.append(f"- [ ] {t['title']}")
        lines.append("")
    if done_tasks:
        lines.append(f"## Recently completed ({len(done_tasks)} tasks)")
        for t in done_tasks[:5]:
            lines.append(f"- [x] {t['title']}")
        lines.append("")
    lines += [
        "## Metis integration",
        "The Metis MCP server (`metis-rc`) tracks this project. Use these tools:",
        f"- `create_task(title=..., project_id=\"{project['project_id']}\")` — add a task",
        "- `get_tasks(project_id=...)` — see open tasks",
        "- `update_project_memory(project_id=..., what_was_done=..., next_steps=...)` — log a session",
        "- `scan_project_folder(project_id=...)` — refresh activity in Metis dashboard",
        "",
        "_Auto-generated by Metis. Re-run `scan_project_folder` to refresh._",
    ]
    target = folder / "CLAUDE.md"
    # GUARD: never clobber a hand-authored CLAUDE.md (the repo's operating guide, or a
    # user's own project file). Only write if the file is absent or was itself a Metis-
    # generated card. This prevents the root CLAUDE.md from being overwritten when a
    # project's folder happens to be the repo root (the metis-dashboard case).
    MARKER = "_Auto-generated by Metis."
    if target.exists():
        try:
            existing = target.read_text(encoding="utf-8", errors="replace")
        except OSError:
            existing = ""
        if MARKER not in existing:
            return False  # hand-authored — leave it alone
    # Extra belt: refuse if this folder is clearly the Metis repo root, not a project.
    if (folder / "system" / "mcp-server").is_dir() and (folder / "agents").is_dir():
        return False
    try:
        target.write_text("\n".join(lines), encoding="utf-8")
        return True
    except OSError:
        return False


# ── MCP tools ─────────────────────────────────────────────────────────────────

@app.tool()
async def scan_project_folder(project_id: str) -> list[TextContent]:
    """Scan a project folder to detect work done since last scan.

    Checks: git commits, modified files, todo completions, new documents.
    Updates the project's scan_summary and last_scanned fields.
    Also refreshes CLAUDE.md in the project folder.
    """
    with connect(paths.db) as conn:
        _ensure_columns(conn)
        row = conn.execute(
            "SELECT project_id, title, description, domain, category, external_path, "
            "next_step, status, last_scanned FROM projects WHERE project_id = ?",
            (project_id,),
        ).fetchone()

    if not row:
        return [TextContent(type="text", text=f"Project not found: {project_id}")]

    folder = _resolve_folder(row["external_path"] or "")
    if not folder:
        return [TextContent(type="text", text=f"Project folder not found: {row['external_path']}")]

    last_scanned = row["last_scanned"]
    now = datetime.datetime.now()
    findings = []

    # ── Git activity ──────────────────────────────────────────────────────────
    if (folder / ".git").exists():
        try:
            since = last_scanned or (now - datetime.timedelta(days=7)).isoformat()
            result = subprocess.run(
                ["git", "log", f"--since={since}", "--oneline", "--no-merges"],
                cwd=str(folder), capture_output=True, text=True, timeout=10
            )
            commits = [l.strip() for l in result.stdout.splitlines() if l.strip()]
            if commits:
                findings.append(f"**Git commits ({len(commits)}):**")
                for c in commits[:8]:
                    findings.append(f"  - {c}")
        except Exception:
            pass

    # ── Modified files ────────────────────────────────────────────────────────
    try:
        cutoff = datetime.datetime.fromisoformat(last_scanned) if last_scanned else now - datetime.timedelta(days=7)
        cutoff_ts = cutoff.timestamp()
        modified = []
        doc_exts = {".md", ".Rmd", ".qmd", ".py", ".R", ".tex", ".docx", ".txt"}
        for f in folder.rglob("*"):
            if f.is_file() and not any(p.startswith(".") for p in f.parts):
                if f.suffix in doc_exts and f.stat().st_mtime > cutoff_ts:
                    modified.append(f.name)
        if modified:
            findings.append(f"**Modified files ({len(modified)}):**")
            for m in modified[:8]:
                findings.append(f"  - {m}")
    except Exception:
        pass

    # ── Todo / planning files ─────────────────────────────────────────────────
    for fname in ["TODO.md", "PLANNING.md", "todo.txt", "tasks.md"]:
        p = folder / fname
        if p.exists():
            try:
                content = p.read_text(encoding="utf-8", errors="ignore")
                done  = len(re.findall(r"- \[x\]", content, re.I))
                open_ = len(re.findall(r"- \[ \]", content, re.I))
                findings.append(f"**{fname}:** {open_} open, {done} done")
            except Exception:
                pass

    # ── Refresh CLAUDE.md ─────────────────────────────────────────────────────
    with connect(paths.db) as conn:
        tasks = [
            dict(r) for r in conn.execute(
                "SELECT title, status FROM tasks WHERE project_id = ? ORDER BY status, created_at DESC",
                (project_id,)
            ).fetchall()
        ]
        scan_summary = "\n".join(findings) if findings else "No new activity detected."
        conn.execute(
            "UPDATE projects SET last_scanned = ?, scan_summary = ? WHERE project_id = ?",
            (now.isoformat(timespec="seconds"), scan_summary, project_id),
        )

    _write_claude_md(folder, dict(row), tasks)

    result = [f"## Scan: {row['title']}", f"Scanned: {folder}", ""]
    if findings:
        result += findings
    else:
        result.append("No new activity since last scan.")
    result += ["", "CLAUDE.md refreshed."]

    return [TextContent(type="text", text="\n".join(result))]


@app.tool()
async def update_all_projects() -> list[TextContent]:
    """Scan all registered project folders for activity. Refreshes CLAUDE.md for each.

    Called by the dashboard Update button or on demand.
    """
    with connect(paths.db) as conn:
        _ensure_columns(conn)
        rows = conn.execute(
            "SELECT project_id, title, external_path FROM projects "
            "WHERE status = 'active' AND external_path IS NOT NULL AND external_path != ''",
        ).fetchall()

    results = []
    scanned = 0
    skipped = 0
    for row in rows:
        folder = _resolve_folder(row["external_path"])
        if not folder:
            skipped += 1
            continue
        # Call scan inline (avoid MCP overhead)
        try:
            await scan_project_folder(row["project_id"])
            results.append(f"✓ {row['title']}")
            scanned += 1
        except Exception as e:
            results.append(f"⚠ {row['title']}: {e}")

    summary = f"Scanned {scanned} project(s), {skipped} folder(s) not found."
    return [TextContent(type="text", text=summary + "\n\n" + "\n".join(results))]


@app.tool()
async def scan_folder_for_intent(
    folder_path: str,
    scan_type: str = "names",
) -> list[TextContent]:
    """Detect a project's purpose from its folder contents.

    Args:
        folder_path: Absolute path to the project folder.
        scan_type: One of:
            "names"   — file/folder names only (fast, no content read)
            "content" — reads README, CLAUDE.md, PLANNING.md (more accurate)
            "none"    — skip scan, return empty (user will describe manually)
    """
    if scan_type == "none":
        return [TextContent(type="text", text="INTENT_SKIP")]

    folder = _resolve_folder(folder_path)
    if not folder:
        return [TextContent(type="text", text=f"Folder not found: {folder_path}")]

    clues = []

    # File type distribution
    ext_counts: dict[str, int] = {}
    try:
        for f in folder.rglob("*"):
            if f.is_file() and not any(p.startswith(".") for p in f.parts[len(folder.parts):]):
                ext_counts[f.suffix.lower()] = ext_counts.get(f.suffix.lower(), 0) + 1
    except Exception:
        pass

    # Category inference from file types
    r_files   = ext_counts.get(".r", 0) + ext_counts.get(".rmd", 0) + ext_counts.get(".qmd", 0)
    py_files  = ext_counts.get(".py", 0)
    doc_files = ext_counts.get(".md", 0) + ext_counts.get(".tex", 0) + ext_counts.get(".docx", 0)
    data_files= ext_counts.get(".csv", 0) + ext_counts.get(".xlsx", 0) + ext_counts.get(".dta", 0)

    if r_files > 3:
        clues.append("R-based analysis" if not doc_files else "article/report with R code")
    if py_files > 3:
        clues.append("Python project")
    if data_files > 0:
        clues.append("data analysis")
    if doc_files > 5:
        clues.append("writing/documentation")
    has_git = (folder / ".git").exists()
    if has_git:
        clues.append("version-controlled")

    # Folder name clues
    name = folder.name.lower()
    if any(w in name for w in ["article", "paper", "manuscript"]):
        clues.insert(0, "scientific article")
    elif any(w in name for w in ["thesis", "phd", "dissertation"]):
        clues.insert(0, "thesis chapter")
    elif any(w in name for w in ["course", "teach", "lecture"]):
        clues.insert(0, "teaching material")
    elif any(w in name for w in ["grant", "proposal", "funding"]):
        clues.insert(0, "grant/proposal")
    elif any(w in name for w in ["app", "tool", "software", "dashboard"]):
        clues.insert(0, "software/tool")
    elif any(w in name for w in ["review", "systematic"]):
        clues.insert(0, "systematic review")

    # Content scan (README, CLAUDE.md, PLANNING.md)
    description_hint = ""
    if scan_type == "content":
        for fname in ["README.md", "CLAUDE.md", "PLANNING.md", "README.txt"]:
            fp = folder / fname
            if fp.exists():
                try:
                    text = fp.read_text(encoding="utf-8", errors="ignore")[:800]
                    # Strip markdown formatting
                    text = re.sub(r"#+\s*", "", text)
                    text = re.sub(r"\*+", "", text)
                    text = text.strip()[:400]
                    if text:
                        description_hint = text
                        break
                except Exception:
                    pass

    summary_parts = []
    if clues:
        summary_parts.append("Type hints: " + ", ".join(dict.fromkeys(clues)))
    if description_hint:
        summary_parts.append("From README: " + description_hint[:200])
    summary_parts.append(f"Files: {sum(ext_counts.values())} total")

    return [TextContent(type="text", text="\n".join(summary_parts) if summary_parts else "No clear intent detected.")]


@app.tool()
async def link_claude_desktop(
    project_id: str,
    write_config: bool = True,
) -> list[TextContent]:
    """Register a Metis project in Claude Desktop's project list.

    Args:
        project_id: The Metis project ID to register.
        write_config: If True, write directly to Claude Desktop config.
                      If False, return instructions for manual setup.
    """
    with connect(paths.db) as conn:
        _ensure_columns(conn)
        row = conn.execute(
            "SELECT project_id, title, description, external_path, category FROM projects "
            "WHERE project_id = ?", (project_id,)
        ).fetchone()

    if not row:
        return [TextContent(type="text", text=f"Project not found: {project_id}")]

    folder = _resolve_folder(row["external_path"] or "")
    folder_win = _wsl_to_windows(str(folder)) if folder else ""

    if not write_config:
        instructions = [
            f"## Manual Claude Desktop setup for: {row['title']}",
            "",
            "1. Open Claude Desktop",
            "2. Click **Projects** in the sidebar",
            "3. Click **New Project**",
            f"4. Name it: `{row['title']}`",
            f"5. Set the project folder to: `{folder_win or row['external_path']}`",
            "6. The CLAUDE.md in that folder will be loaded automatically",
            "",
            "Once created, Metis will track this project automatically.",
        ]
        return [TextContent(type="text", text="\n".join(instructions))]

    # Find Claude Desktop config
    win_appdata = os.environ.get("APPDATA", "")
    if not win_appdata:
        # Try to get from Windows via cmd.exe (WSL)
        try:
            result = subprocess.run(
                ["cmd.exe", "/c", "echo %APPDATA%"],
                capture_output=True, text=True, timeout=5
            )
            win_appdata = result.stdout.strip().strip("\r\n")
        except Exception:
            pass

    config_path = None
    if win_appdata:
        win_config = Path(win_appdata) / "Claude" / "claude_desktop_config.json"
        wsl_config = Path(_windows_to_wsl(str(win_config)))
        for p in [win_config, wsl_config]:
            if p.exists():
                config_path = p
                break

    if not config_path:
        return [TextContent(
            type="text",
            text=(
                "Claude Desktop config not found. "
                "Make sure Claude Desktop is installed and has been opened at least once.\n\n"
                "Manual setup: open Claude Desktop → Projects → New Project → "
                f"set folder to: {folder_win or row['external_path']}"
            )
        )]

    try:
        cfg = json.loads(config_path.read_text(encoding="utf-8"))
    except Exception:
        cfg = {}

    cfg.setdefault("projects", [])
    existing_ids = [p.get("id") for p in cfg["projects"]]
    if project_id not in existing_ids:
        cfg["projects"].append({
            "id": project_id,
            "name": row["title"],
            "description": row["description"] or "",
            "folder": folder_win or row["external_path"] or "",
        })
        config_path.write_text(json.dumps(cfg, indent=2), encoding="utf-8")

    with connect(paths.db) as conn:
        conn.execute(
            "UPDATE projects SET claude_desktop_linked = 1 WHERE project_id = ?",
            (project_id,),
        )

    return [TextContent(
        type="text",
        text=(
            f"Project '{row['title']}' registered in Claude Desktop.\n"
            "Restart Claude Desktop to see it in the sidebar."
        )
    )]


@app.tool()
async def get_project_categories() -> list[TextContent]:
    """Return all distinct project categories currently in use.

    Lists the user-defined categories (e.g. "Article", "Grant", "Teaching")
    that have been assigned to projects, so you can group projects or offer
    an existing category before set_project_category invents a new one.

    Takes no arguments.

    Returns:
        A text line listing the distinct non-empty categories in alphabetical
        order, or a message that none are defined yet.
    """
    with connect(paths.db) as conn:
        _ensure_columns(conn)
        rows = conn.execute(
            "SELECT DISTINCT category FROM projects WHERE category IS NOT NULL AND category != '' ORDER BY category"
        ).fetchall()

    cats = [r["category"] for r in rows]
    if not cats:
        return [TextContent(type="text", text="No categories defined yet.")]
    return [TextContent(type="text", text="Categories: " + ", ".join(cats))]


@app.tool()
async def set_project_category(project_id: str, category: str) -> list[TextContent]:
    """Assign or change a project's category.

    Sets the grouping label on a project so it sorts with related work on the
    dashboard. Call get_project_categories first to reuse an existing label
    rather than creating a near-duplicate.

    Args:
        project_id: The project_id of the project to update.
        category: The category label to assign (e.g. "Article", "Grant");
            surrounding whitespace is trimmed.

    Returns:
        A confirmation message naming the category and project that were set.
    """
    with connect(paths.db) as conn:
        _ensure_columns(conn)
        conn.execute(
            "UPDATE projects SET category = ? WHERE project_id = ?",
            (category.strip(), project_id),
        )
    return [TextContent(type="text", text=f"Category set to '{category}' for project {project_id}.")]


@app.tool()
async def create_project_full(
    title: str,
    folder_path: str = "",
    category: str = "",
    description: str = "",
    scan_type: str = "names",
    link_claude_desktop_auto: bool = True,
) -> list[TextContent]:
    """Create a project with full Metis integration: DB record, CLAUDE.md, Claude Desktop.

    This is the unified project creation tool used by all installers and the dashboard.

    Args:
        title:        Project name.
        folder_path:  Absolute path to the project folder on disk.
        category:     User-defined category (e.g. 'Article', 'Grant', 'Teaching').
        description:  What this project is about. If empty and scan_type != 'none',
                      auto-detected from folder.
        scan_type:    'names' | 'content' | 'none' — how to infer description from folder.
        link_claude_desktop_auto: Write project to Claude Desktop config automatically.
    """
    import re as _re
    import datetime as _dt

    project_id = _re.sub(r"[^\w\s-]", "", title.lower())
    project_id = _re.sub(r"[\s_-]+", "-", project_id).strip("-")[:60]
    now = _dt.datetime.now().isoformat(timespec="seconds")

    folder = _resolve_folder(folder_path) if folder_path else None

    # Auto-detect description from folder if not provided
    if not description and folder and scan_type != "none":
        try:
            intent_result = await scan_folder_for_intent(str(folder), scan_type)
            detected = intent_result[0].text if intent_result else ""
            if detected and detected != "INTENT_SKIP":
                description = detected[:300]
        except Exception:
            pass

    with connect(paths.db) as conn:
        _ensure_columns(conn)

        existing = conn.execute(
            "SELECT project_id FROM projects WHERE project_id = ?", (project_id,)
        ).fetchone()

        if existing:
            # Update folder/category if provided
            updates = []
            params = []
            if folder_path:
                updates.append("external_path = ?")
                params.append(folder_path)
            if category:
                updates.append("category = ?")
                params.append(category)
            if updates:
                params.append(project_id)
                conn.execute(
                    f"UPDATE projects SET {', '.join(updates)} WHERE project_id = ?",
                    params,
                )
            lines = [f"Project already exists: '{title}' — updated with new settings."]
        else:
            conn.execute(
                """INSERT INTO projects
                   (project_id, title, description, domain, category, external_path,
                    status, priority, next_step, created_at, source)
                   VALUES (?, ?, ?, ?, ?, ?, 'active', 'medium', '', ?, 'installer')""",
                (project_id, title, description, category, category,
                 folder_path, now),
            )
            lines = [f"Project created: '{title}' (id: {project_id})"]

        tasks = []  # no tasks yet on creation

    # Write CLAUDE.md
    if folder:
        project_row = {
            "project_id": project_id, "title": title, "description": description,
            "category": category, "domain": category, "status": "active", "next_step": "",
        }
        if _write_claude_md(folder, project_row, tasks):
            lines.append(f"CLAUDE.md written to {folder}")

    # Register in Claude Desktop
    if link_claude_desktop_auto and folder_path:
        try:
            cd_result = await link_claude_desktop(project_id, write_config=True)
            lines.append(cd_result[0].text)
        except Exception as e:
            lines.append(f"Claude Desktop registration: {e} (run link_claude_desktop manually)")

    return [TextContent(type="text", text="\n".join(lines))]
