"""Handoff brief — Phase 8.13.

Generates a portable markdown brief that captures enough state for the next
session (or a different AI / device) to resume without re-loading conversation
history. Pure function plus an `@app.tool()` MCP wrapper.

The brief deliberately stays under ~3 KB so it can be pasted into a fresh
context window cheaply.
"""

import datetime
import os
from pathlib import Path

from mcp.types import TextContent

from metis_mcp.app_instance import app
from metis_mcp.config import paths
from metis_mcp.db import connect


def _rc_root() -> Path:
    rc = os.environ.get("METIS_RC_ROOT", "")
    if rc:
        return Path(rc)
    # Fall back to the repo path inferred from this file
    return Path(__file__).resolve().parents[5] / "metis"


def _journal_dir() -> Path:
    p = _rc_root() / "journal"
    p.mkdir(parents=True, exist_ok=True)
    return p


def _tokens_today() -> int:
    today_iso = datetime.date.today().isoformat()
    try:
        with connect(paths.db) as conn:
            row = conn.execute(
                "SELECT COALESCE(SUM(COALESCE(input_tokens,0) + COALESCE(output_tokens,0)), 0) "
                "FROM agent_runs WHERE DATE(created_at) = ?",
                (today_iso,),
            ).fetchone()
        return int(row[0] or 0) if row else 0
    except Exception:
        return 0


def _recent_agent_runs(limit: int = 8) -> list[dict]:
    try:
        with connect(paths.db) as conn:
            rows = conn.execute(
                "SELECT agent_slug, task_summary, status, created_at, "
                "COALESCE(input_tokens,0) + COALESCE(output_tokens,0) as toks "
                "FROM agent_runs ORDER BY created_at DESC LIMIT ?",
                (limit,),
            ).fetchall()
        return [dict(r) for r in rows]
    except Exception:
        return []


def _active_projects(limit: int = 6) -> list[dict]:
    try:
        with connect(paths.db) as conn:
            rows = conn.execute(
                "SELECT project_id, title, next_step, priority "
                "FROM projects WHERE status='active' "
                "ORDER BY CASE priority WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END, "
                "created_at DESC LIMIT ?",
                (limit,),
            ).fetchall()
        return [dict(r) for r in rows]
    except Exception:
        return []


def _open_tasks(limit: int = 8) -> list[dict]:
    try:
        with connect(paths.db) as conn:
            rows = conn.execute(
                "SELECT task_id, title, due_date, status FROM tasks "
                "WHERE status NOT IN ('done','cancelled','paused') "
                "ORDER BY due_date NULLS LAST, created_at DESC LIMIT ?",
                (limit,),
            ).fetchall()
        return [dict(r) for r in rows]
    except Exception:
        return []


def _last_journal() -> str:
    journal = _journal_dir()
    candidates = sorted(journal.glob("*.md"), reverse=True)
    if not candidates:
        return ""
    return candidates[0].name


def _phase_status() -> str:
    p = _rc_root() / "system" / "config" / "implementation-progress.json"
    if not p.exists():
        return "implementation-progress.json not found"
    try:
        import json
        data = json.loads(p.read_text(encoding="utf-8"))
        meta = data.get("_meta", {})
        return (
            f"last_updated: {meta.get('last_updated', '?')} · "
            f"last_phase: {meta.get('last_phase_completed', '?')}"
        )
    except Exception:
        return "implementation-progress.json unreadable"


def generate_handoff_brief(session_id: str | None = None,
                           write_to_journal: bool = True) -> dict:
    """Build a session handoff brief and optionally persist it.

    Returns a dict with keys: ``status``, ``path`` (relative), ``preview``,
    ``tokens_today``, ``runs_count``.
    """
    today = datetime.date.today().isoformat()
    tokens = _tokens_today()
    runs = _recent_agent_runs(8)
    projects = _active_projects(6)
    tasks = _open_tasks(8)
    last_journal = _last_journal()
    phase = _phase_status()

    lines: list[str] = []
    lines.append(f"# Session handoff — {today}")
    lines.append("")
    lines.append(
        "> Auto-generated by `generate_handoff_brief`. Read this first when "
        "resuming a session or switching AI/device. Designed to be < 3 KB so "
        "it fits in a fresh context window cheaply."
    )
    lines.append("")
    lines.append("## Quick state")
    lines.append("")
    lines.append(f"- **Tokens used today**: {tokens:,}")
    lines.append(f"- **Phase tracker**: {phase}")
    if session_id:
        lines.append(f"- **Session id**: `{session_id}`")
    if last_journal:
        lines.append(f"- **Most recent journal entry**: `journal/{last_journal}`")
    lines.append("")

    if projects:
        lines.append("## Active projects")
        lines.append("")
        for p in projects:
            ns = (p.get("next_step") or "").strip()
            ns_part = f" — _next: {ns}_" if ns else ""
            lines.append(f"- **{p.get('title') or p.get('project_id')}**{ns_part}")
        lines.append("")

    if tasks:
        lines.append("## Open tasks (top 8)")
        lines.append("")
        for t in tasks:
            due = (t.get("due_date") or "")[:10]
            due_part = f" (due {due})" if due else ""
            lines.append(f"- {t.get('title')}{due_part}")
        lines.append("")

    if runs:
        lines.append("## Recent agent runs")
        lines.append("")
        for r in runs:
            when = (r.get("created_at") or "")[:16].replace("T", " ")
            toks = r.get("toks") or 0
            tail = f" · {toks // 1000}K toks" if toks >= 1000 else ""
            lines.append(
                f"- `{when}` **{r.get('agent_slug')}** — "
                f"{(r.get('task_summary') or '')[:90]}{tail}"
            )
        lines.append("")

    lines.append("## How to resume")
    lines.append("")
    lines.append(
        "1. `/clear` your prior session if you haven't already.\n"
        "2. Open this file as the first read of the new session.\n"
        "3. Pick the next item from the active-projects or open-tasks list.\n"
        "4. If unsure, run `/metis_status` for a fresh routing check."
    )
    lines.append("")
    body = "\n".join(lines)

    path_str = ""
    if write_to_journal:
        try:
            out = _journal_dir() / f"{today}_session_handoff_auto.md"
            out.write_text(body, encoding="utf-8")
            try:
                rc = _rc_root()
                path_str = str(out.relative_to(rc.parent))
            except Exception:
                path_str = str(out)
        except Exception as e:
            return {
                "status": "error",
                "message": f"Could not write handoff: {e}",
                "preview": body[:280],
            }

    return {
        "status": "ok",
        "path": path_str,
        "preview": body[:280],
        "tokens_today": tokens,
        "runs_count": len(runs),
    }


@app.tool()
async def generate_handoff_brief_tool(session_id: str = "") -> list[TextContent]:
    """Generate a portable session handoff brief.

    Captures: tokens used today, active projects, open tasks, recent agent
    runs, and the most recent journal entry. Writes to
    `metis/journal/YYYY-MM-DD_session_handoff_auto.md` and returns the brief.

    Use this when a session is approaching its end, before `/clear`, or when
    switching to another AI / device.
    """
    result = generate_handoff_brief(session_id or None, write_to_journal=True)
    if result["status"] == "ok":
        msg = (
            f"Handoff brief written to `{result['path']}` — "
            f"{result['runs_count']} recent runs, "
            f"{result['tokens_today']:,} tokens used today.\n\n"
            f"Preview:\n\n{result['preview']}…"
        )
    else:
        msg = result.get("message", "handoff failed") + "\n\n" + result.get("preview", "")
    return [TextContent(type="text", text=msg)]
