#!/bin/bash
# setup-mcp.sh — Install / reinstall the Metis MCP server on WSL Ubuntu.
#
# Works on Ubuntu 20.04 (Python 3.8), 22.04 (3.10), 24.04 (3.12).
# Installs a dedicated venv at ~/.local/share/metis-mcp/.venv
# so the NTFS OneDrive path never needs to manage symlinks.
#
# Run once after a fresh WSL install or when adding new tool modules:
#   bash setup-mcp.sh

set -euo pipefail

# ── Install profile ──────────────────────────────────────────────────────────
# Choose how much of Metis to install:
#   light    — MCP server only. Works with Claude Desktop + Claude Code. ~5 min.
#   standard — MCP server + Python dashboard (9-tab UI). ~15 min. (DEFAULT)
#   full     — Standard + Windows Task Scheduler automation + daily scan. ~25 min.
#
# Override via environment: METIS_PROFILE=light bash setup-mcp.sh
METIS_PROFILE="${METIS_PROFILE:-}"

if [ -z "$METIS_PROFILE" ] && [ -t 0 ]; then
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  Metis Install Profile"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  [1] light    — MCP server only (~5 min)"
  echo "  [2] standard — MCP server + dashboard (~15 min)  [DEFAULT]"
  echo "  [3] full     — Standard + Windows scheduler (~25 min)"
  echo ""
  read -rp "  Choose profile [1/2/3, Enter for standard]: " PROFILE_CHOICE
  case "$PROFILE_CHOICE" in
    1) METIS_PROFILE="light" ;;
    3) METIS_PROFILE="full" ;;
    *) METIS_PROFILE="standard" ;;
  esac
elif [ -z "$METIS_PROFILE" ]; then
  METIS_PROFILE="standard"
fi

echo "Installing Metis with profile: $METIS_PROFILE"

# ── Config ──────────────────────────────────────────────────────────────────
VENV_DIR="$HOME/.local/share/metis-mcp/.venv"
RUN_SCRIPT="$HOME/.local/share/metis-mcp/run.sh"
METIS_RC_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SRC_DIR="$METIS_RC_ROOT/system/mcp-server"

# ── Detect Python ────────────────────────────────────────────────────────────
# Prefer Python 3.12, fall back to 3.11, 3.10, 3.9
PYTHON=""
for candidate in python3.12 python3.11 python3.10 python3.9 python3; do
  if command -v "$candidate" >/dev/null 2>&1; then
    VER=$("$candidate" -c "import sys; print('%d.%d' % sys.version_info[:2])" 2>/dev/null)
    MAJOR=${VER%%.*}; MINOR=${VER#*.}
    if [ "$MAJOR" -ge 3 ] && [ "$MINOR" -ge 9 ]; then
      PYTHON="$candidate"
      break
    fi
  fi
done

if [ -z "$PYTHON" ]; then
  echo "ERROR: Python 3.9+ not found. Install it first:"
  echo "  Ubuntu 22.04: sudo apt install python3.12"
  echo "  Ubuntu 20.04: sudo apt install python3.10"
  exit 1
fi

PYTHON_PATH=$(command -v "$PYTHON")
echo "Using Python: $PYTHON_PATH ($($PYTHON --version))"

# ── Install Python 3.12 if missing and on Ubuntu 22+ ─────────────────────────
if ! command -v python3.12 >/dev/null 2>&1; then
  if grep -q "22.04\|24.04" /etc/os-release 2>/dev/null; then
    echo "Installing python3.12 via deadsnakes PPA..."
    sudo apt-get update -q
    sudo apt-get install -y software-properties-common
    sudo add-apt-repository -y ppa:deadsnakes/ppa
    sudo apt-get update -q
    sudo apt-get install -y python3.12 python3.12-venv
    PYTHON_PATH=$(command -v python3.12)
  fi
fi

# ── Create venv ──────────────────────────────────────────────────────────────
mkdir -p "$HOME/.local/share/metis-mcp"

if [ -d "$VENV_DIR" ]; then
  echo "Existing venv found at $VENV_DIR — updating packages only."
  VENV_PYTHON="$VENV_DIR/bin/python3"
  if [ ! -f "$VENV_PYTHON" ]; then
    echo "Venv appears broken — recreating..."
    rm -rf "$VENV_DIR"
  fi
fi

if [ ! -d "$VENV_DIR" ]; then
  echo "Creating venv at $VENV_DIR..."
  "$PYTHON_PATH" -m venv "$VENV_DIR"
fi

# ── Upgrade pip inside venv ──────────────────────────────────────────────────
"$VENV_DIR/bin/pip" install --quiet --upgrade pip setuptools wheel

# ── Install dependencies ─────────────────────────────────────────────────────
echo "Installing requirements..."
if [ -f "$SRC_DIR/requirements.txt" ]; then
  "$VENV_DIR/bin/pip" install --quiet -r "$SRC_DIR/requirements.txt"
else
  "$VENV_DIR/bin/pip" install --quiet -e "$SRC_DIR"
fi

# ── Install package in editable mode ─────────────────────────────────────────
echo "Installing metis-mcp-server (editable)..."
"$VENV_DIR/bin/pip" install --quiet -e "$SRC_DIR"

# ── Install dashboard (app-py) dependencies into same venv ───────────────────
# Skipped on 'light' profile — dashboard not included.
if [ "$METIS_PROFILE" != "light" ]; then
  APP_REQ="$METIS_RC_ROOT/system/app-py/requirements.txt"
  if [ -f "$APP_REQ" ]; then
    echo "Installing dashboard dependencies..."
    "$VENV_DIR/bin/pip" install --quiet -r "$APP_REQ"
    echo "  Dashboard deps installed"
  fi
else
  echo "Skipping dashboard install (light profile)"
fi

# ── Write run.sh ─────────────────────────────────────────────────────────────
cat > "$RUN_SCRIPT" <<RUNSH
#!/bin/bash
# Auto-generated by setup-mcp.sh — do not edit manually.
VENV_DIR="$VENV_DIR"
export METIS_RC_ROOT="$METIS_RC_ROOT"
exec "\$VENV_DIR/bin/python3" -m metis_mcp.server
RUNSH
chmod +x "$RUN_SCRIPT"
echo "run.sh written to $RUN_SCRIPT"

# ── Verify ──────────────────────────────────────────────────────────────────
echo ""
echo "Verifying import..."
if "$VENV_DIR/bin/python3" -c "import metis_mcp.server; print('  metis_mcp.server import OK')" 2>&1; then
  TOOL_COUNT=$("$VENV_DIR/bin/python3" -c "
import metis_mcp.server
from metis_mcp.app_instance import app
tools = list(app._tool_manager._tools.keys()) if hasattr(app, '_tool_manager') else []
print(len(tools))
" 2>/dev/null || echo "?")
  echo "  $TOOL_COUNT tools registered"
else
  echo "  ERROR: import failed — see above"
  exit 1
fi

# ── Auto-register with Claude Code ──────────────────────────────────────────
# Claude Code stores MCP servers in ~/.claude.json (per-project) via `claude mcp add`.
# ~/.claude/settings.json is used only for permissions (tool auto-approval).
CC_SETTINGS="$HOME/.claude/settings.json"
mkdir -p "$HOME/.claude"

# Register the server via the CLI (writes to ~/.claude.json for this project)
if command -v claude >/dev/null 2>&1; then
  # Remove old registration first to avoid duplicates, then re-add
  claude mcp remove metis-rc 2>/dev/null || true
  if claude mcp add metis-rc "$RUN_SCRIPT" 2>/dev/null; then
    echo "  Claude Code: registered metis-rc via claude mcp add"
  else
    echo "  Claude Code: mcp add failed — you may need to run: claude mcp add metis-rc $RUN_SCRIPT"
  fi
else
  echo "  Claude Code CLI not found — skipping auto-registration"
  echo "  Once installed, run: claude mcp add metis-rc $RUN_SCRIPT"
fi

# Write permissions to settings.json so MCP tools are auto-approved
python3 - <<PYEOF
import json, os

path = "$CC_SETTINGS"
os.makedirs(os.path.dirname(path), exist_ok=True)

s = {}
if os.path.exists(path):
    with open(path) as f:
        s = json.load(f)

# Remove legacy mcpServers key (now handled by claude mcp add)
s.pop("mcpServers", None)

# Ensure mcp__metis-rc__* tools are auto-approved
s.setdefault("permissions", {}).setdefault("allow", [])
if "mcp__metis-rc__*" not in s["permissions"]["allow"]:
    s["permissions"]["allow"].append("mcp__metis-rc__*")

with open(path, "w") as f:
    json.dump(s, f, indent=2)
print("  Claude Code: permissions updated in ~/.claude/settings.json")
PYEOF

# ── Auto-register with Claude Desktop (Windows) ──────────────────────────────
WIN_USER=$(cmd.exe /c "echo %USERNAME%" 2>/dev/null | tr -d '\r\n')
CD_CONFIG="/mnt/c/Users/$WIN_USER/AppData/Roaming/Claude/claude_desktop_config.json"

if [ -f "$CD_CONFIG" ]; then
  python3 - <<PYEOF
import json, sys

path = "$CD_CONFIG"
run_script = "$RUN_SCRIPT"

with open(path) as f:
    cfg = json.load(f)

cfg.setdefault("mcpServers", {})["metis-rc"] = {
    "command": "wsl",
    "args": ["-e", run_script],
    "autoApprove": ["*"]
}

with open(path, "w") as f:
    json.dump(cfg, f, indent=2)
print("  Claude Desktop: updated claude_desktop_config.json")
PYEOF
else
  echo "  Claude Desktop config not found at $CD_CONFIG — skipping (Claude Desktop may not be installed)"
fi

# ── Initialize DB if not present ─────────────────────────────────────────────
DB_PATH="$METIS_RC_ROOT/system/app/data/metis.sqlite"
INIT_SCRIPT="$METIS_RC_ROOT/system/installer/init_db.py"
if [ ! -f "$DB_PATH" ] && [ -f "$INIT_SCRIPT" ]; then
  echo "Initializing database..."
  "$VENV_DIR/bin/python3" "$INIT_SCRIPT"
fi

# ── Create Windows desktop shortcut ─────────────────────────────────────────
BAT_PATH=$(wslpath -w "$METIS_RC_ROOT/system/launch-metis.bat" 2>/dev/null || true)
ICO_PATH=$(wslpath -w "$METIS_RC_ROOT/system/install/windows/metis-brain.ico" 2>/dev/null || true)
WORK_PATH=$(wslpath -w "$METIS_RC_ROOT/system" 2>/dev/null || true)
if [ -n "$BAT_PATH" ]; then
  powershell.exe -Command "
\$ws = New-Object -ComObject WScript.Shell
\$desktopRoot = [System.Environment]::GetFolderPath('Desktop')
# OneDrive may redirect Desktop — find actual .lnk location
\$desktopOneDrive = [System.Environment]::GetFolderPath('UserProfile') + '\OneDrive - ITG\Desktop'
\$dests = @()
if (Test-Path \$desktopOneDrive) { \$dests += \$desktopOneDrive + '\Metis.lnk' }
\$dests += \$desktopRoot + '\Metis.lnk'
\$dests += [System.Environment]::GetFolderPath('Programs') + '\Metis.lnk'
foreach (\$dest in \$dests) {
  \$sc = \$ws.CreateShortcut(\$dest)
  \$sc.TargetPath = '$BAT_PATH'
  \$sc.WorkingDirectory = '$WORK_PATH'
  \$sc.IconLocation = '$ICO_PATH,0'
  \$sc.Description = 'Metis Research Cortex Dashboard'
  \$sc.WindowStyle = 7
  \$sc.Save()
}
Write-Host '  Shortcuts: Desktop + Start Menu created'
" 2>/dev/null || echo "  Shortcuts: could not create (PowerShell unavailable)"
fi

# ── Write install-state.json ─────────────────────────────────────────────────
INSTALL_STATE="$METIS_RC_ROOT/system/config/install-state.json"
DASHBOARD_INSTALLED="false"
[ "$METIS_PROFILE" != "light" ] && DASHBOARD_INSTALLED="true"
HOOKS_INSTALLED="false"
[ -f "$METIS_RC_ROOT/.claude/settings.json" ] && HOOKS_INSTALLED="true"
cat > "$INSTALL_STATE" <<STATEEOF
{
  "profile": "$METIS_PROFILE",
  "version": "1.0.0",
  "installed_at": "$(date -I)",
  "components": {
    "mcp_server": true,
    "dashboard": $DASHBOARD_INSTALLED,
    "hooks": $HOOKS_INSTALLED,
    "windows_task_scheduler": false,
    "nssm_service": false,
    "docker": false
  },
  "notes": "Written by setup-mcp.sh. Update 'components' manually if you add optional components."
}
STATEEOF
echo "  install-state.json written"

echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "  Setup complete (profile: $METIS_PROFILE)."
echo "  Restart Claude Code and Claude Desktop for changes to take effect."
echo "════════════════════════════════════════════════════════════════════"
