#!/bin/bash
# run-dashboard.sh — start the Metis dashboard. Tracked in git; works on any machine.
#
# WHY THIS FILE EXISTS
#   The launcher everything calls (metis-boot.sh, the Windows shortcut, the Docker
#   entrypoint) was system/app-py/run.sh — gitignored and generated by nothing.
#   A computer set up from git had no way to start or supervise the dashboard.
#   This is that launcher, path-independent. A local run.sh still wins where one
#   exists, so a machine with its own tuned copy is never overridden by a pull.
#
# THE INVARIANTS (each was a real outage — see tests/reliability/test_supervision.py)
#   * Singleton via `flock` on fd 9.
#   * Every long-lived child is spawned with `9>&-`. A child that inherits fd 9
#     holds the launch lock for its whole life while serving nothing, and every
#     later launch fails — the dashboard becomes permanently un-restartable.
#   * The loser of the lock RETRIES and, if the holder serves nothing, takes over.
#     It never just exits 1: that is what made the old wedge permanent.
#
# ENV
#   METIS_PORT        dashboard port (default 8080)
#   METIS_VENV        venv holding the MCP package (default ~/.local/share/metis-mcp/.venv)
#   METIS_COURSE_APP  Node course app to keep alive alongside (default ~/mlm-app)

set -u

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$APP_DIR/../.." && pwd)"
PORT="${METIS_PORT:-8080}"
VENV="${METIS_VENV:-$HOME/.local/share/metis-mcp/.venv}"
PY="$VENV/bin/python3"
[ -x "$PY" ] || PY="$(command -v python3)"
LOCK="$APP_DIR/.metis-launch.lock"

export METIS_RC_ROOT="${METIS_RC_ROOT:-$ROOT}"
export PYTHONPATH="$ROOT/system/mcp-server/src:$APP_DIR${PYTHONPATH:+:$PYTHONPATH}"
# The embedding model is pre-cached by the installer; never block start-up on a
# network fetch.
export HF_HUB_OFFLINE="${HF_HUB_OFFLINE:-1}"

say() { echo "[run-dashboard] $*"; }
healthy() { curl -sf -m 5 "http://127.0.0.1:$PORT/health" >/dev/null 2>&1; }

# PIDs holding an fd on the lock — via /proc, so a holder of a since-replaced
# inode ("(deleted)") is found too.
lock_holders() {
    local d pid
    for d in /proc/[0-9]*; do
        pid="${d#/proc/}"
        [ "$pid" = "$$" ] && continue
        ls -l "$d/fd" 2>/dev/null | grep -q -- "$LOCK" && echo "$pid"
    done
}

# ── 1. The singleton lock ────────────────────────────────────────────────────
exec 9>"$LOCK"
got_lock=0
for _ in $(seq 1 60); do
    if flock -n 9; then
        got_lock=1
        break
    fi
    if healthy; then
        say "dashboard already serving on :$PORT — nothing to do"
        exit 0
    fi
    sleep 2   # a dying supervisor or a starting one: give it a moment
done

if [ "$got_lock" = 0 ]; then
    # Held for two minutes and nothing serves: the holder is stale.
    say "lock held but nothing serving on :$PORT — taking over"
    for pid in $(lock_holders); do
        kill "$pid" 2>/dev/null
    done
    sleep 2
    # A holder that ignored SIGTERM keeps the old inode; a fresh file is a fresh lock.
    rm -f "$LOCK"
    exec 9>"$LOCK"
    if ! flock -w 10 9; then
        say "could not take the launch lock"
        exit 1
    fi
fi

# ── 2. The course server (optional) ──────────────────────────────────────────
COURSE_APP="${METIS_COURSE_APP:-$HOME/mlm-app}"
COURSE_LOG="/tmp/metis-course-server.log"
WATCHDOG=""
if [ -f "$COURSE_APP/server.js" ] && command -v node >/dev/null 2>&1; then
    if ! pgrep -f "^(\S*/)?node .*server\.js" >/dev/null 2>&1; then
        (cd "$COURSE_APP" && nohup node server.js </dev/null >>"$COURSE_LOG" 2>&1 9>&- &)
    fi
    # Keep it alive. The subshell itself must also drop fd 9 — it lives as long
    # as the dashboard and serves nothing.
    (
        while sleep 60; do
            pgrep -f "^(\S*/)?node .*server\.js" >/dev/null 2>&1 && continue
            (cd "$COURSE_APP" && nohup node server.js </dev/null >>"$COURSE_LOG" 2>&1 9>&- &)
        done
    ) 9>&- &
    WATCHDOG=$!
fi
trap '[ -n "$WATCHDOG" ] && kill "$WATCHDOG" 2>/dev/null' EXIT

# ── 3. The dashboard ─────────────────────────────────────────────────────────
# Not exec'd: the trap above must outlive uvicorn to stop the watchdog. uvicorn
# keeps fd 9 — it is the one process that SHOULD hold the lock, because it serves.
cd "$APP_DIR" || exit 1
echo "$PORT" > "$APP_DIR/.metis-port"   # read by the Windows launchers
say "starting on :$PORT"
"$PY" -m uvicorn main:app --host 127.0.0.1 --port "$PORT"
