#!/bin/bash
# setup-mcp.sh — Install / reinstall the Metis MCP server on WSL Ubuntu.
#
# Works on Ubuntu 20.04 (Python 3.8), 22.04 (3.10), 24.04 (3.12).
# Installs a dedicated venv at ~/.local/share/metis-mcp/.venv
# so the NTFS OneDrive path never needs to manage symlinks.
#
# Run once after a fresh WSL install or when adding new tool modules:
#   bash setup-mcp.sh

set -euo pipefail

# ── Config ──────────────────────────────────────────────────────────────────
VENV_DIR="$HOME/.local/share/metis-mcp/.venv"
RUN_SCRIPT="$HOME/.local/share/metis-mcp/run.sh"
METIS_RC_ROOT="/mnt/c/Users/sverschaeve/OneDrive - ITG/Documents/7. Software/Research Cortex/metis"
SRC_DIR="$METIS_RC_ROOT/system/mcp-server"

# ── Detect Python ────────────────────────────────────────────────────────────
# Prefer Python 3.12, fall back to 3.11, 3.10, 3.9
PYTHON=""
for candidate in python3.12 python3.11 python3.10 python3.9 python3; do
  if command -v "$candidate" >/dev/null 2>&1; then
    VER=$("$candidate" -c "import sys; print('%d.%d' % sys.version_info[:2])" 2>/dev/null)
    MAJOR=${VER%%.*}; MINOR=${VER#*.}
    if [ "$MAJOR" -ge 3 ] && [ "$MINOR" -ge 9 ]; then
      PYTHON="$candidate"
      break
    fi
  fi
done

if [ -z "$PYTHON" ]; then
  echo "ERROR: Python 3.9+ not found. Install it first:"
  echo "  Ubuntu 22.04: sudo apt install python3.12"
  echo "  Ubuntu 20.04: sudo apt install python3.10"
  exit 1
fi

PYTHON_PATH=$(command -v "$PYTHON")
echo "Using Python: $PYTHON_PATH ($($PYTHON --version))"

# ── Install Python 3.12 if missing and on Ubuntu 22+ ─────────────────────────
if ! command -v python3.12 >/dev/null 2>&1; then
  if grep -q "22.04\|24.04" /etc/os-release 2>/dev/null; then
    echo "Installing python3.12 via deadsnakes PPA..."
    sudo apt-get update -q
    sudo apt-get install -y software-properties-common
    sudo add-apt-repository -y ppa:deadsnakes/ppa
    sudo apt-get update -q
    sudo apt-get install -y python3.12 python3.12-venv
    PYTHON_PATH=$(command -v python3.12)
  fi
fi

# ── Create venv ──────────────────────────────────────────────────────────────
mkdir -p "$HOME/.local/share/metis-mcp"

if [ -d "$VENV_DIR" ]; then
  echo "Existing venv found at $VENV_DIR — updating packages only."
  VENV_PYTHON="$VENV_DIR/bin/python3"
  if [ ! -f "$VENV_PYTHON" ]; then
    echo "Venv appears broken — recreating..."
    rm -rf "$VENV_DIR"
  fi
fi

if [ ! -d "$VENV_DIR" ]; then
  echo "Creating venv at $VENV_DIR..."
  "$PYTHON_PATH" -m venv "$VENV_DIR"
fi

# ── Upgrade pip inside venv ──────────────────────────────────────────────────
"$VENV_DIR/bin/pip" install --quiet --upgrade pip setuptools wheel

# ── Install dependencies ─────────────────────────────────────────────────────
echo "Installing requirements..."
if [ -f "$SRC_DIR/requirements.txt" ]; then
  "$VENV_DIR/bin/pip" install --quiet -r "$SRC_DIR/requirements.txt"
else
  "$VENV_DIR/bin/pip" install --quiet -e "$SRC_DIR"
fi

# ── Install package in editable mode ─────────────────────────────────────────
echo "Installing metis-mcp-server (editable)..."
"$VENV_DIR/bin/pip" install --quiet -e "$SRC_DIR"

# ── Write run.sh ─────────────────────────────────────────────────────────────
cat > "$RUN_SCRIPT" <<RUNSH
#!/bin/bash
# Auto-generated by setup-mcp.sh — do not edit manually.
VENV_DIR="$VENV_DIR"
export METIS_RC_ROOT="$METIS_RC_ROOT"
exec "\$VENV_DIR/bin/python3" -m metis_mcp.server
RUNSH
chmod +x "$RUN_SCRIPT"
echo "run.sh written to $RUN_SCRIPT"

# ── Verify ──────────────────────────────────────────────────────────────────
echo ""
echo "Verifying import..."
if "$VENV_DIR/bin/python3" -c "import metis_mcp.server; print('  metis_mcp.server import OK')" 2>&1; then
  TOOL_COUNT=$("$VENV_DIR/bin/python3" -c "
import metis_mcp.server
from metis_mcp.app_instance import app
tools = list(app._tool_manager._tools.keys()) if hasattr(app, '_tool_manager') else []
print(len(tools))
" 2>/dev/null || echo "?")
  echo "  $TOOL_COUNT tools registered"
else
  echo "  ERROR: import failed — see above"
  exit 1
fi

# ── Print Claude Code / Claude Desktop registration ──────────────────────────
cat <<REG

────────────────────────────────────────────────────────────────────
Setup complete. Register the MCP server:

  Claude Code:
    Add to ~/.claude/settings.json:
      "mcpServers": { "metis-rc": { "command": "$RUN_SCRIPT" } }

  Claude Desktop (Windows):
    Add to %APPDATA%\Claude\claude_desktop_config.json:
      "mcpServers": {
        "metis-rc": {
          "command": "wsl",
          "args": ["-e", "$RUN_SCRIPT"]
        }
      }

────────────────────────────────────────────────────────────────────
REG
